#!/usr/bin/env bash


module load gnu7
module load cuda/11.1.1
module load anaconda
module load mvapich2
module load pmix/2.2.2

source activate timsTF

srun -n2 --mpi=pmi2 --mem=50000 --gres=gpu:1 --pty bash
